* use c++ casting functions
casting at all isn't recommended really, but we'll use this for now

* use constexpr where it can be used

* use nullptr instead of null

* use proper way to import c headers

* change pcssb.c to pcssb.cpp

get this error:

clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
pcssb.cpp:131:17: error: cannot initialize a variable of type 'char *const' with an rvalue of type 'void *'
  131 |     char *const audioData = malloc(dataSize * sizeof(char));
      |                 ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:26: pcssb] Error 1